version: "3"

services:
  server-toolbox-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-toolbox-test
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules